# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rulem < Formula
  desc "AI Assistant Instruction Manager CLI"
  homepage "https://github.com/muhammadbassiony/rulem"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/muhammadbassiony/Rulem/releases/download/v0.1.0/Rulem_Darwin_x86_64.tar.gz"
      sha256 "ef26728c5d6458e2ce192d750d7bab60d1545f7a0debbabd80a57731dc46e08b"

      def install
        bin.install "rulem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/muhammadbassiony/Rulem/releases/download/v0.1.0/Rulem_Darwin_arm64.tar.gz"
      sha256 "ab9a98a544c376fb680d2fe65d4080f90a75e099f79122944928795bc680e0bb"

      def install
        bin.install "rulem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/muhammadbassiony/Rulem/releases/download/v0.1.0/Rulem_Linux_x86_64.tar.gz"
      sha256 "b01f257da8d49ef6f1805dc7ef2edf1183d44ad6f992d025503ad2a27e7fbf9d"
      def install
        bin.install "rulem"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/muhammadbassiony/Rulem/releases/download/v0.1.0/Rulem_Linux_arm64.tar.gz"
      sha256 "cf88e4d20b8d2440a37149eb4c9820f744d685f62fbdaff6103efc98e6d06da3"
      def install
        bin.install "rulem"
      end
    end
  end

  test do
    system "#{bin}/rulem --version"
  end
end
