# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rulem < Formula
  desc "AI Assistant Instruction Manager CLI"
  homepage "https://github.com/muhammadbassiony/rulem"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/muhammadbassiony/Rulem/releases/download/v0.1.1/Rulem_Darwin_x86_64.tar.gz"
      sha256 "f8c43d60a76ef1845f1d5e18f0cc30ef3b679c736a1215f9ddab680b7718bb34"

      def install
        bin.install "rulem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/muhammadbassiony/Rulem/releases/download/v0.1.1/Rulem_Darwin_arm64.tar.gz"
      sha256 "ee0c4b0acd174aee9ce57a3aa4410496b1ca3de706aa5375b63d59b62afe6db5"

      def install
        bin.install "rulem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/muhammadbassiony/Rulem/releases/download/v0.1.1/Rulem_Linux_x86_64.tar.gz"
      sha256 "c85fa27651dad1a0aeff346e880db73b6fd3a7f94de0a772805d7c64185df68c"
      def install
        bin.install "rulem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muhammadbassiony/Rulem/releases/download/v0.1.1/Rulem_Linux_arm64.tar.gz"
      sha256 "024279fdecd972fb27d1726f6690369ab4fa75375d326aeec776a04e46aa24f9"
      def install
        bin.install "rulem"
      end
    end
  end

  test do
    system "#{bin}/rulem --version"
  end
end
